# Form implementation generated from reading ui file 'storymaster/view/lorekeeper/lorekeeper.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LorekeeperWindow(object):
    def setupUi(self, LorekeeperWindow):
        LorekeeperWindow.setObjectName("LorekeeperWindow")
        LorekeeperWindow.resize(1150, 620)
        self.centralwidget = QtWidgets.QWidget(parent=LorekeeperWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout_4.addWidget(self.listView)
        self.listView_2 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_4.addWidget(self.listView_2)
        self.formLayout.setLayout(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.verticalLayout_4
        )
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tableView
        )
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        LorekeeperWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LorekeeperWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        LorekeeperWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LorekeeperWindow)
        self.statusbar.setObjectName("statusbar")
        LorekeeperWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=LorekeeperWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtGui.QAction(parent=LorekeeperWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(parent=LorekeeperWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtGui.QAction(parent=LorekeeperWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=LorekeeperWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(LorekeeperWindow)
        QtCore.QMetaObject.connectSlotsByName(LorekeeperWindow)

    def retranslateUi(self, LorekeeperWindow):
        _translate = QtCore.QCoreApplication.translate
        LorekeeperWindow.setWindowTitle(_translate("LorekeeperWindow", "Lorekeeper"))
        self.menuFile.setTitle(_translate("LorekeeperWindow", "File"))
        self.menuEdit.setTitle(_translate("LorekeeperWindow", "Edit"))
        self.actionNew.setText(_translate("LorekeeperWindow", "New"))
        self.actionLoad.setText(_translate("LorekeeperWindow", "Load"))
        self.actionSave.setText(_translate("LorekeeperWindow", "Save"))
        self.actionUndo.setText(_translate("LorekeeperWindow", "Undo"))
        self.actionRedo.setText(_translate("LorekeeperWindow", "Redo"))
