# UTF-8
# Version info file for PyInstaller
# This file is automatically generated and should be in the correct format for PyInstaller

# PyInstaller will provide these imports during build
# For standalone testing, we provide dummy implementations
try:
    from PyInstaller.utils.win32.versioninfo import (
        VSVersionInfo, FixedFileInfo, StringFileInfo, StringTable, 
        StringStruct, VarFileInfo, VarStruct
    )
except ImportError:
    # Dummy classes for testing
    class Dummy:
        def __init__(self, *args, **kwargs): pass
    VSVersionInfo = FixedFileInfo = StringFileInfo = StringTable = Dummy
    StringStruct = VarFileInfo = VarStruct = Dummy

# Version info structure - PyInstaller expects this exact variable name
version_info = VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(1,0,0,0),
    prodvers=(1,0,0,0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(u'040904B0', [
        StringStruct(u'CompanyName', u'Storymaster Development'),
        StringStruct(u'FileDescription', u'Storymaster - Creative Writing Tool'),
        StringStruct(u'FileVersion', u'1.0.0.0'),
        StringStruct(u'InternalName', u'storymaster'),
        StringStruct(u'LegalCopyright', u'Copyright (C) 2025'),
        StringStruct(u'OriginalFilename', u'storymaster.exe'),
        StringStruct(u'ProductName', u'Storymaster'),
        StringStruct(u'ProductVersion', u'1.0.0.0')
      ])
    ]), 
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
