# Form implementation generated from reading ui file 'storymaster/view/litographer/litographer.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LitographerWindow(object):
    def setupUi(self, LitographerWindow):
        LitographerWindow.setObjectName("LitographerWindow")
        LitographerWindow.resize(990, 600)
        self.centralwidget = QtWidgets.QWidget(parent=LitographerWindow)
        self.centralwidget.setObjectName("centralwidget")
        LitographerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LitographerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        LitographerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LitographerWindow)
        self.statusbar.setObjectName("statusbar")
        LitographerWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(LitographerWindow)
        QtCore.QMetaObject.connectSlotsByName(LitographerWindow)

    def retranslateUi(self, LitographerWindow):
        _translate = QtCore.QCoreApplication.translate
        LitographerWindow.setWindowTitle(_translate("LitographerWindow", "Litographer"))
        self.menuFile.setTitle(_translate("LitographerWindow", "File"))
