#!/usr/bin/env python3
"""
Create a proper Windows version info file for PyInstaller
This generates the version_info.py file with proper imports
"""

def create_version_info():
    """Create version_info.py file"""
    version_content = '''# -*- coding: utf-8 -*-
"""
Windows version information for Storymaster executable
Auto-generated by create_version_info.py
"""

# Import version info structures
try:
    from PyInstaller.utils.win32.versioninfo import (
        VSVersionInfo, FixedFileInfo, StringFileInfo, StringTable, 
        StringStruct, VarFileInfo, VarStruct
    )
except ImportError:
    # Fallback for older PyInstaller versions
    try:
        from PyInstaller.utils.win32 import versioninfo
        VSVersionInfo = versioninfo.VSVersionInfo
        FixedFileInfo = versioninfo.FixedFileInfo
        StringFileInfo = versioninfo.StringFileInfo
        StringTable = versioninfo.StringTable
        StringStruct = versioninfo.StringStruct
        VarFileInfo = versioninfo.VarFileInfo
        VarStruct = versioninfo.VarStruct
    except ImportError:
        # Create dummy classes if version info is not available
        class DummyVersionInfo:
            def __init__(self, *args, **kwargs):
                pass
        
        VSVersionInfo = DummyVersionInfo
        FixedFileInfo = DummyVersionInfo
        StringFileInfo = DummyVersionInfo
        StringTable = DummyVersionInfo
        StringStruct = DummyVersionInfo
        VarFileInfo = DummyVersionInfo
        VarStruct = DummyVersionInfo

# Version info structure
version_info = VSVersionInfo(
    ffi=FixedFileInfo(
        filevers=(1, 0, 0, 0),
        prodvers=(1, 0, 0, 0),
        mask=0x3F,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    "040904B0",
                    [
                        StringStruct("CompanyName", "Storymaster Development"),
                        StringStruct("FileDescription", "Storymaster - Creative Writing Tool"),
                        StringStruct("FileVersion", "1.0.0.0"),
                        StringStruct("InternalName", "storymaster"),
                        StringStruct("LegalCopyright", "Copyright (C) 2025"),
                        StringStruct("OriginalFilename", "storymaster.exe"),
                        StringStruct("ProductName", "Storymaster"),
                        StringStruct("ProductVersion", "1.0.0.0"),
                    ],
                )
            ]
        ),
        VarFileInfo([VarStruct("Translation", [1033, 1200])]),
    ],
)
'''
    
    with open('version_info.py', 'w', encoding='utf-8') as f:
        f.write(version_content)
    
    print("✓ Created version_info.py")
    return True

if __name__ == "__main__":
    create_version_info()