# Form implementation generated from reading ui file 'storymaster/view/character_arcs/arc_type_manager_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcTypeManagerDialog(object):
    def setupUi(self, ArcTypeManagerDialog):
        ArcTypeManagerDialog.setObjectName("ArcTypeManagerDialog")
        ArcTypeManagerDialog.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArcTypeManagerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ArcTypeManagerDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.addArcTypeButton = QtWidgets.QPushButton(parent=ArcTypeManagerDialog)
        self.addArcTypeButton.setObjectName("addArcTypeButton")
        self.toolbarLayout.addWidget(self.addArcTypeButton)
        self.editArcTypeButton = QtWidgets.QPushButton(parent=ArcTypeManagerDialog)
        self.editArcTypeButton.setEnabled(False)
        self.editArcTypeButton.setObjectName("editArcTypeButton")
        self.toolbarLayout.addWidget(self.editArcTypeButton)
        self.deleteArcTypeButton = QtWidgets.QPushButton(parent=ArcTypeManagerDialog)
        self.deleteArcTypeButton.setEnabled(False)
        self.deleteArcTypeButton.setObjectName("deleteArcTypeButton")
        self.toolbarLayout.addWidget(self.deleteArcTypeButton)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.toolbarLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.toolbarLayout)
        self.arcTypesTable = QtWidgets.QTableWidget(parent=ArcTypeManagerDialog)
        self.arcTypesTable.setAlternatingRowColors(True)
        self.arcTypesTable.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.arcTypesTable.setObjectName("arcTypesTable")
        self.arcTypesTable.setColumnCount(2)
        self.arcTypesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.arcTypesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.arcTypesTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.arcTypesTable)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ArcTypeManagerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Close
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArcTypeManagerDialog)
        self.buttonBox.rejected.connect(ArcTypeManagerDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ArcTypeManagerDialog)

    def retranslateUi(self, ArcTypeManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        ArcTypeManagerDialog.setWindowTitle(
            _translate("ArcTypeManagerDialog", "Manage Arc Types")
        )
        self.titleLabel.setText(
            _translate("ArcTypeManagerDialog", "Arc Type Management")
        )
        self.addArcTypeButton.setText(
            _translate("ArcTypeManagerDialog", "Add Arc Type")
        )
        self.editArcTypeButton.setText(
            _translate("ArcTypeManagerDialog", "Edit Arc Type")
        )
        self.deleteArcTypeButton.setText(
            _translate("ArcTypeManagerDialog", "Delete Arc Type")
        )
        self.arcTypesTable.setSortingEnabled(True)
        item = self.arcTypesTable.horizontalHeaderItem(0)
        item.setText(_translate("ArcTypeManagerDialog", "Name"))
        item = self.arcTypesTable.horizontalHeaderItem(1)
        item.setText(_translate("ArcTypeManagerDialog", "Description"))
