# Form implementation generated from reading ui file 'storymaster/view/character_arcs/arc_type_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcTypeDialog(object):
    def setupUi(self, ArcTypeDialog):
        ArcTypeDialog.setObjectName("ArcTypeDialog")
        ArcTypeDialog.resize(400, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArcTypeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ArcTypeDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(parent=ArcTypeDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(parent=ArcTypeDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.descriptionLabel = QtWidgets.QLabel(parent=ArcTypeDialog)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descriptionLabel)
        self.descriptionEdit = QtWidgets.QTextEdit(parent=ArcTypeDialog)
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.descriptionEdit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ArcTypeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArcTypeDialog)
        self.buttonBox.accepted.connect(ArcTypeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ArcTypeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ArcTypeDialog)

    def retranslateUi(self, ArcTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        ArcTypeDialog.setWindowTitle(_translate("ArcTypeDialog", "Arc Type"))
        self.titleLabel.setText(_translate("ArcTypeDialog", "Add/Edit Arc Type"))
        self.nameLabel.setText(_translate("ArcTypeDialog", "Name:"))
        self.descriptionLabel.setText(_translate("ArcTypeDialog", "Description:"))
