# Form implementation generated from reading ui file 'storymaster/view/character_arcs/arc_point_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcPointDialog(object):
    def setupUi(self, ArcPointDialog):
        ArcPointDialog.setObjectName("ArcPointDialog")
        ArcPointDialog.resize(500, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArcPointDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ArcPointDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.scrollArea = QtWidgets.QScrollArea(parent=ArcPointDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.orderLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.orderLabel.setObjectName("orderLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.orderLabel
        )
        self.orderSpinBox = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.orderSpinBox.setMinimum(1)
        self.orderSpinBox.setMaximum(999)
        self.orderSpinBox.setObjectName("orderSpinBox")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.orderSpinBox
        )
        self.titleArcLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleArcLabel.setObjectName("titleArcLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titleArcLabel
        )
        self.titleEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.titleEdit
        )
        self.nodeLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.nodeLabel.setObjectName("nodeLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nodeLabel
        )
        self.nodeComboBox = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.nodeComboBox.setObjectName("nodeComboBox")
        self.nodeComboBox.addItem("")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nodeComboBox
        )
        self.descriptionLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descriptionLabel
        )
        self.descriptionEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.descriptionEdit
        )
        self.emotionalStateLabel = QtWidgets.QLabel(
            parent=self.scrollAreaWidgetContents
        )
        self.emotionalStateLabel.setObjectName("emotionalStateLabel")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emotionalStateLabel
        )
        self.emotionalStateEdit = QtWidgets.QTextEdit(
            parent=self.scrollAreaWidgetContents
        )
        self.emotionalStateEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.emotionalStateEdit.setObjectName("emotionalStateEdit")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.emotionalStateEdit
        )
        self.relationshipsLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.relationshipsLabel.setObjectName("relationshipsLabel")
        self.formLayout.setWidget(
            7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.relationshipsLabel
        )
        self.relationshipsEdit = QtWidgets.QTextEdit(
            parent=self.scrollAreaWidgetContents
        )
        self.relationshipsEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.relationshipsEdit.setObjectName("relationshipsEdit")
        self.formLayout.setWidget(
            8, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.relationshipsEdit
        )
        self.goalsLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.goalsLabel.setObjectName("goalsLabel")
        self.formLayout.setWidget(
            9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.goalsLabel
        )
        self.goalsEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.goalsEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.goalsEdit.setObjectName("goalsEdit")
        self.formLayout.setWidget(
            10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.goalsEdit
        )
        self.conflictLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.conflictLabel.setObjectName("conflictLabel")
        self.formLayout.setWidget(
            11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.conflictLabel
        )
        self.conflictEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.conflictEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.conflictEdit.setObjectName("conflictEdit")
        self.formLayout.setWidget(
            12, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.conflictEdit
        )
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ArcPointDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArcPointDialog)
        self.buttonBox.accepted.connect(ArcPointDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(ArcPointDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ArcPointDialog)

    def retranslateUi(self, ArcPointDialog):
        _translate = QtCore.QCoreApplication.translate
        ArcPointDialog.setWindowTitle(_translate("ArcPointDialog", "Arc Point"))
        self.titleLabel.setText(_translate("ArcPointDialog", "Add/Edit Arc Point"))
        self.orderLabel.setText(_translate("ArcPointDialog", "Order Index:"))
        self.titleArcLabel.setText(_translate("ArcPointDialog", "Title:"))
        self.nodeLabel.setText(_translate("ArcPointDialog", "Story Node:"))
        self.nodeComboBox.setItemText(0, _translate("ArcPointDialog", "No Node"))
        self.descriptionLabel.setText(_translate("ArcPointDialog", "Description:"))
        self.emotionalStateLabel.setText(
            _translate("ArcPointDialog", "Emotional State:")
        )
        self.relationshipsLabel.setText(
            _translate("ArcPointDialog", "Character Relationships:")
        )
        self.goalsLabel.setText(_translate("ArcPointDialog", "Goals:"))
        self.conflictLabel.setText(_translate("ArcPointDialog", "Internal Conflict:"))
