"""Database for storio. all the submodules"""

from storio.model.database.schema.base import Projects, Users
from storio.model.database.schema.connective_database import (
    LitographyNoteToLorekeeperActor,
    LitographyNoteToLorekeeperBackground,
    LitographyNoteToLorekeeperFaction,
    LitographyNoteToLorekeeperHistory,
    LitographyNoteToLorekeeperLocation,
    LitographyNoteToLorekeeperObject,
    LitographyNoteToLorekeeperWorldData,
)
from storio.model.database.schema.lito_database import (
    NodeType,
    NoteType,
    PlotSectionType,
)
from storio.model.database.schema.lore_database import (
    Actor,
    ActorAOnBRelations,
    ActorToSkills,
    Background,
    Class_,
    Faction,
    FactionAOnBRelations,
    FactionMembers,
    History,
    HistoryActor,
    HistoryFaction,
    HistoryLocation,
    HistoryObject,
    HistoryWorldData,
    Location,
    LocationCity,
    LocationCityDistricts,
    LocationDungeon,
    LocationFloraFauna,
    LocationToFaction,
    Object_,
    ObjectToOwner,
    Race,
    Resident,
    Skills,
    SubRace,
    WorldData,
)

__all__ = [
    "Users",
    "Projects",
    "PlotSectionType",
    "NoteType",
    "NodeType",
    "Class_",
    "Background",
    "Race",
    "SubRace",
    "Actor",
    "ActorAOnBRelations",
    "Skills",
    "ActorToSkills",
    "Faction",
    "FactionAOnBRelations",
    "FactionMembers",
    "Location",
    "LocationToFaction",
    "LocationDungeon",
    "LocationCity",
    "LocationCityDistricts",
    "Resident",
    "LocationFloraFauna",
    "History",
    "HistoryActor",
    "HistoryLocation",
    "HistoryFaction",
    "HistoryObject",
    "HistoryWorldData",
    "Object_",
    "ObjectToOwner",
    "WorldData",
    "LitographyNoteToLorekeeperActor",
    "LitographyNoteToLorekeeperBackground",
    "LitographyNoteToLorekeeperFaction",
    "LitographyNoteToLorekeeperLocation",
    "LitographyNoteToLorekeeperHistory",
    "LitographyNoteToLorekeeperObject",
    "LitographyNoteToLorekeeperWorldData",
]
