# Form implementation generated from reading ui file './storymaster/view/common/storymaster_main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StorymasterMainWindow(object):
    def setupUi(self, StorymasterMainWindow):
        StorymasterMainWindow.setObjectName("StorymasterMainWindow")
        StorymasterMainWindow.resize(1280, 720)
        StorymasterMainWindow.setStyleSheet("/* --- Dark Theme inspired by DaVinci Resolve ---\n"
"*/\n"
"\n"
"QWidget {\n"
"    background-color: #2e2e2e; /* Dark gray base */\n"
"    color: #dcdcdc; /* Light gray text */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #1e1e1e; /* Even darker for the main window background */\n"
"}\n"
"\n"
"/* --- Stacked Widget & Pages --- */\n"
"QStackedWidget > QWidget {\n"
"    background-color: #252525; /* Slightly lighter background for the main content area */\n"
"}\n"
"\n"
"/* --- Bottom Navigation Bar --- */\n"
"#bottomNavBar {\n"
"    background-color: #1e1e1e;\n"
"    border-top: 1px solid #424242;\n"
"}\n"
"\n"
"#bottomNavBar QPushButton {\n"
"    background-color: transparent;\n"
"    color: #a0a0a0;\n"
"    border: none;\n"
"    padding: 8px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"#bottomNavBar QPushButton:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#bottomNavBar QPushButton:checked {\n"
"    background-color: #505050;\n"
"    color: #ffffff;\n"
"    border-bottom: 2px solid #af80f8; /* A nice accent color */\n"
"}\n"
"\n"
"/* --- Menu, Tool, and Status Bars --- */\n"
"QMenuBar {\n"
"    background-color: #2e2e2e;\n"
"    color: #dcdcdc;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #505050;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #2e2e2e;\n"
"    border: 1px solid #424242;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #505050;\n"
"}\n"
"\n"
"QToolBar {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #2e2e2e;\n"
"    border-top: 1px solid #424242;\n"
"}\n"
"\n"
"/* --- Widgets inside pages --- */\n"
"QSplitter::handle {\n"
"    background-color: #424242;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"/* --- Table and Tree View Enhancements --- */\n"
"QTableView {\n"
"    background-color: #2e2e2e;\n"
"    border: 1px solid #424242;\n"
"    selection-background-color: #5c4a8e; /* A darker purple for selection */\n"
"    selection-color: #ffffff; /* White text on selection */\n"
"    gridline-color: #383838; /* Subtle grid lines */\n"
"    alternate-background-color: #333333; /* For alternating rows */\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 5px;\n"
"    border-style: none; /* Remove individual item borders */\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: #4a4a4a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #222222; /* Darker header */\n"
"    color: #dcdcdc;\n"
"    padding: 4px; /* Reduced padding for a smaller header */\n"
"    border: none; /* Remove default borders */\n"
"    border-bottom: 1px solid #424242;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Style the top-left corner button of the table */\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #222222;\n"
"    border-bottom: 1px solid #424242;\n"
"}\n"
"\n"
"/* Tree view specific styles to keep it clean */\n"
"QTreeView {\n"
"    background-color: #2e2e2e;\n"
"    border: 1px solid #424242;\n"
"    selection-background-color: #5c4a8e;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"    background-color: #4a4a4a;\n"
"}\n"
"\n"
"/* --- Edit Form Styling --- */\n"
"QScrollArea {\n"
"    border: none;\n"
"}\n"
"\n"
"#editFormWidget {\n"
"    background-color: #222222;\n"
"    border: 1px solid #424242;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#editFormWidget QLabel {\n"
"    font-weight: bold;\n"
"    color: #a0a0a0;\n"
"}\n"
"\n"
"#editFormWidget QLineEdit, #editFormWidget QTextEdit {\n"
"    background-color: #2e2e2e;\n"
"    border: 1px solid #424242;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#editFormWidget QLineEdit:focus, #editFormWidget QTextEdit:focus {\n"
"    border: 1px solid #af80f8;\n"
"}\n"
"\n"
"#editFormWidget QPushButton {\n"
"    background-color: #5c4a8e;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#editFormWidget QPushButton:hover {\n"
"    background-color: #6c5ab8;\n"
"}\n"
"\n"
"\n"
"QGraphicsView {\n"
"    border-radius: 4px;\n"
"    border: 1px solid #424242;\n"
"}\n"
"\n"
"QLabel#pageTitleLabel {\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(parent=StorymasterMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pageStack = QtWidgets.QStackedWidget(parent=self.centralWidget)
        self.pageStack.setObjectName("pageStack")
        self.litographerPage = QtWidgets.QWidget()
        self.litographerPage.setObjectName("litographerPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.litographerPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pageTitleLabel = QtWidgets.QLabel(parent=self.litographerPage)
        self.pageTitleLabel.setObjectName("pageTitleLabel")
        self.verticalLayout_2.addWidget(self.pageTitleLabel)
        self.nodeGraphView = QtWidgets.QGraphicsView(parent=self.litographerPage)
        self.nodeGraphView.setObjectName("nodeGraphView")
        self.verticalLayout_2.addWidget(self.nodeGraphView)
        self.pageStack.addWidget(self.litographerPage)
        self.lorekeeperPage = QtWidgets.QWidget()
        self.lorekeeperPage.setObjectName("lorekeeperPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.lorekeeperPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pageTitleLabel_2 = QtWidgets.QLabel(parent=self.lorekeeperPage)
        self.pageTitleLabel_2.setObjectName("pageTitleLabel_2")
        self.verticalLayout_4.addWidget(self.pageTitleLabel_2)
        self.lorekeeperSplitter = QtWidgets.QSplitter(parent=self.lorekeeperPage)
        self.lorekeeperSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.lorekeeperSplitter.setObjectName("lorekeeperSplitter")
        self.horizontalSplitter = QtWidgets.QSplitter(parent=self.lorekeeperSplitter)
        self.horizontalSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSplitter.setObjectName("horizontalSplitter")
        self.databaseTreeView = QtWidgets.QTreeView(parent=self.horizontalSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseTreeView.sizePolicy().hasHeightForWidth())
        self.databaseTreeView.setSizePolicy(sizePolicy)
        self.databaseTreeView.setMinimumSize(QtCore.QSize(200, 0))
        self.databaseTreeView.setAlternatingRowColors(False)
        self.databaseTreeView.setObjectName("databaseTreeView")
        self.databaseTableView = QtWidgets.QTableView(parent=self.horizontalSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseTableView.sizePolicy().hasHeightForWidth())
        self.databaseTableView.setSizePolicy(sizePolicy)
        self.databaseTableView.setAlternatingRowColors(True)
        self.databaseTableView.setObjectName("databaseTableView")
        self.editFormScrollArea = QtWidgets.QScrollArea(parent=self.lorekeeperSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.editFormScrollArea.sizePolicy().hasHeightForWidth())
        self.editFormScrollArea.setSizePolicy(sizePolicy)
        self.editFormScrollArea.setMinimumSize(QtCore.QSize(0, 150))
        self.editFormScrollArea.setWidgetResizable(True)
        self.editFormScrollArea.setObjectName("editFormScrollArea")
        self.editFormWidget = QtWidgets.QWidget()
        self.editFormWidget.setGeometry(QtCore.QRect(0, 0, 1278, 148))
        self.editFormWidget.setObjectName("editFormWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.editFormWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.editFormLayout = QtWidgets.QFormLayout()
        self.editFormLayout.setObjectName("editFormLayout")
        self.verticalLayout_5.addLayout(self.editFormLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.saveChangesButton = QtWidgets.QPushButton(parent=self.editFormWidget)
        self.saveChangesButton.setObjectName("saveChangesButton")
        self.verticalLayout_5.addWidget(self.saveChangesButton)
        self.editFormScrollArea.setWidget(self.editFormWidget)
        self.verticalLayout_4.addWidget(self.lorekeeperSplitter)
        self.pageStack.addWidget(self.lorekeeperPage)
        self.verticalLayout.addWidget(self.pageStack)
        self.bottomNavBar = QtWidgets.QWidget(parent=self.centralWidget)
        self.bottomNavBar.setMinimumSize(QtCore.QSize(0, 40))
        self.bottomNavBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bottomNavBar.setObjectName("bottomNavBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottomNavBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.litographerNavButton = QtWidgets.QPushButton(parent=self.bottomNavBar)
        self.litographerNavButton.setCheckable(True)
        self.litographerNavButton.setChecked(True)
        self.litographerNavButton.setAutoExclusive(True)
        self.litographerNavButton.setObjectName("litographerNavButton")
        self.navButtonGroup = QtWidgets.QButtonGroup(StorymasterMainWindow)
        self.navButtonGroup.setObjectName("navButtonGroup")
        self.navButtonGroup.addButton(self.litographerNavButton)
        self.horizontalLayout.addWidget(self.litographerNavButton)
        self.lorekeeperNavButton = QtWidgets.QPushButton(parent=self.bottomNavBar)
        self.lorekeeperNavButton.setCheckable(True)
        self.lorekeeperNavButton.setAutoExclusive(True)
        self.lorekeeperNavButton.setObjectName("lorekeeperNavButton")
        self.navButtonGroup.addButton(self.lorekeeperNavButton)
        self.horizontalLayout.addWidget(self.lorekeeperNavButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.bottomNavBar)
        StorymasterMainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(parent=StorymasterMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        StorymasterMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StorymasterMainWindow)
        self.statusbar.setObjectName("statusbar")
        StorymasterMainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionAbout = QtGui.QAction(parent=StorymasterMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(StorymasterMainWindow)
        self.pageStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(StorymasterMainWindow)

    def retranslateUi(self, StorymasterMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StorymasterMainWindow.setWindowTitle(_translate("StorymasterMainWindow", "Storymaster"))
        self.pageTitleLabel.setText(_translate("StorymasterMainWindow", "Litographer - Node Editor"))
        self.pageTitleLabel_2.setText(_translate("StorymasterMainWindow", "Lorekeeper - Database"))
        self.saveChangesButton.setText(_translate("StorymasterMainWindow", "Save Changes"))
        self.litographerNavButton.setText(_translate("StorymasterMainWindow", "Litographer"))
        self.lorekeeperNavButton.setText(_translate("StorymasterMainWindow", "Lorekeeper"))
        self.menuFile.setTitle(_translate("StorymasterMainWindow", "File"))
        self.menuEdit.setTitle(_translate("StorymasterMainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("StorymasterMainWindow", "Help"))
        self.actionNew.setText(_translate("StorymasterMainWindow", "New"))
        self.actionOpen.setText(_translate("StorymasterMainWindow", "Open"))
        self.actionSave.setText(_translate("StorymasterMainWindow", "Save"))
        self.actionSave_As.setText(_translate("StorymasterMainWindow", "Save As..."))
        self.actionExit.setText(_translate("StorymasterMainWindow", "Exit"))
        self.actionUndo.setText(_translate("StorymasterMainWindow", "Undo"))
        self.actionRedo.setText(_translate("StorymasterMainWindow", "Redo"))
        self.actionAbout.setText(_translate("StorymasterMainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StorymasterMainWindow = QtWidgets.QMainWindow()
    ui = Ui_StorymasterMainWindow()
    ui.setupUi(StorymasterMainWindow)
    StorymasterMainWindow.show()
    sys.exit(app.exec())
